export const AGREEMENT_GUIDE_IMAGES = [
  require('../assets/images/guides/agreement/01.jpg'),
  require('../assets/images/guides/agreement/02.jpg'),
  require('../assets/images/guides/agreement/03.jpg'),
  require('../assets/images/guides/agreement/04.jpg'),
  require('../assets/images/guides/agreement/05.jpg'),
  require('../assets/images/guides/agreement/06.jpg'),
  require('../assets/images/guides/agreement/07.jpg'),
  require('../assets/images/guides/agreement/08.jpg'),
  require('../assets/images/guides/agreement/09.jpg'),
] as const;

export const APPOINTMENT_GUIDE_IMAGES = [
  require('../assets/images/guides/appointment/img2.jpg'),
  require('../assets/images/guides/appointment/img3.jpg'),
  require('../assets/images/guides/appointment/img4.jpg'),
  require('../assets/images/guides/appointment/img5.jpg'),
  require('../assets/images/guides/appointment/img6.jpg'),
  require('../assets/images/guides/appointment/img7.jpg'),
  require('../assets/images/guides/appointment/img8.jpg'),
  require('../assets/images/guides/appointment/img9.jpg'),
  require('../assets/images/guides/appointment/img10.jpg'),
  require('../assets/images/guides/appointment/img11.jpg'),
  require('../assets/images/guides/appointment/img12.jpg'),
  require('../assets/images/guides/appointment/img13.jpg'),
  require('../assets/images/guides/appointment/img14.jpg'),
  require('../assets/images/guides/appointment/img15.jpg'),
  require('../assets/images/guides/appointment/img16.jpg'),
  require('../assets/images/guides/appointment/img17.jpg'),
  require('../assets/images/guides/appointment/img18.jpg'),
  require('../assets/images/guides/appointment/img19.jpg'),
  require('../assets/images/guides/appointment/img20.jpg'),
  require('../assets/images/guides/appointment/img21.jpg'),
  require('../assets/images/guides/appointment/img22.jpg'),
  require('../assets/images/guides/appointment/img23.jpg'),
  require('../assets/images/guides/appointment/img24.jpg'),
  require('../assets/images/guides/appointment/img25.jpg'),
] as const;
